### ISSUE TITLE
Answering a question does not redirect to new question

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-mobile#41]
If a user answers a question, he will not be redirected to the next question. Instead the disabled question is shown with a message, that the answer is already given.

![error1](https://cloud.githubusercontent.com/assets/5081579/10415907/257313e4-6fff-11e5-97dc-ca23ddaecb59.png)

Isn't it a better solution to revert behaviour and show the next available question, as it has been some weeks ago? Or is this new behaviour an error?

**Comment by kqc-real** [comment]
Not a bug, but a feature. Users complained that they didn't notice the green tick at the right answer option as the page did not scroll down to that position, but vanished sidewards. So we thought, just give them some time to see the assessments.
