### ISSUE TITLE
LaTeX code in response stats

### ISSUE THREAD

**Issue by mjg** [thm-projects/arsnova-mobile#57]
LaTeX code is allowed in answers for multiple choice questions, the answer renders nicely.

But when the answer is used as a label for the response statistic the label shows the LaTeX code verbatim, not rendered as a LaTeX formula.

**Comment by dgerhardt** [comment]
We know about this issue but unfortunately there is no easy way to fix it. The library we use for formula rendering (MathJax) does not support rendering in HTML5 canvases we use for charts.

One solution would be an automated creation of a chart legend in case of formula use in answer options. Formulas could be mapped to letters which are then used in the chart.

As a workaround for now, this can be done manually be defining a legend as part of the question.
