### ISSUE TITLE
How can I run the mobile App on Android ?

### ISSUE THREAD

**Issue by khalilmebarkia** [thm-projects/arsnova-mobile#58]
Hi,
I tried to run the application on web browser, it works fine. I would like to run it on my android device, I didn't find how to generate the APK file using Grunt and phonegap.
Could you please help me to figure out this problem using any methods you have.
Thank you

**Comment by dgerhardt** [comment]
ARSnova Mobile is implemented as a mobile web application which is run in a browser. As of now,  we do not use Sencha Cmd's capability to create mobile app packages so we have not implemented support for this scenario in our build script.

You might be able to package an app by directly invoking Sencha Cmd. See http://docs.sencha.com/cmd/6.x/cordova_phonegap.html for more information.
