### ISSUE TITLE
Change LDAP Icon

### ISSUE THREAD

**Issue by deada92** [thm-projects/arsnova-mobile#59]
Hello Arsnova-Team,

So I tried to change the LDAP-Icon but it doesn't take effect. In my Arsnova-Propertie file I have this: 

`security.ldap.image=resources/images/rub_label52.png`

At this exact location the launch screen image is also located and arsnova displays it without any issues. 

Does the image has to be in a specific type and size? Atm its .png & 52x52 small..

Any hints what may be the problem?

**Comment by tekay** [comment]
Hello,

did you restart the backend? Changes made to the properties file only take effect when starting the backend.

**Comment by deada92** [comment]
Yes I did.. I always restart the backend. I even restarted the whole server..

**Comment by dgerhardt** [comment]
Since the introduction of the modern theme in ARSnova Mobile 2.1 this setting is no longer working. We should remove this setting or at least add a comment about this.

Beginning with ARSnova Mobile 2.3 you can replace login icons by modifying the theme (`src/main/webapp/resources/sass/_theme.scss`). Add the following code to replace the LDAP icon:

```
.iconBtnImg.login-icon-ldap {
	margin: 0 !important;
	width: 100% !important;
	height: 100% !important;
	background: url(resources/images/rub_label52.png) no-repeat center center; color: transparent;
}
```

**Comment by deada92** [comment]
thx @dgerhardt, I'm I right that I have to build arsnova from source then??

**Comment by dgerhardt** [comment]
That's right. We will discuss whether we can reintroduce this setting in a later release.

**Comment by deada92** [comment]
Does Arsnova Mobile still require Sencha CMD 4.0.48??

**Comment by dgerhardt** [comment]
Yes. There''s currently no reason for us to migrate since the changes of the newest version focus on ExtJS.

**Comment by Rillke** [comment]
I'd appreciate if I could load a custom css file specified in `arsnova.properties`.

**Comment by deada92** [comment]
@Rillke you can add your css like I did in #70
