### ISSUE TITLE
How can I access to the mobile app remotely ?

### ISSUE THREAD

**Issue by khalilmebarkia** [thm-projects/arsnova-mobile#60]
Hi,
 I would like to access to the mobile app remotely from another machine, I launch " Grunt Run" after that I access from another machine.

Thank you

**Comment by dgerhardt** [comment]
By default, `grunt run` makes the app accessible from `localhost` only. The command is a shorthand for `grunt run dev localhost`. You can replace `localhost` with `0.0.0.0` to change this behavior: `grunt run dev 0.0.0.0`

**Comment by khalilmebarkia** [comment]
Thank you for your replying.
I've tried but it doesn't  work.
`MacBook-Air:mobile-app km$ grunt run dev 0.0.0.0 `
`Warning: Task "dev" not found. Use --force to continue. `
`Aborted due to warnings. `

`Execution Time (2016-05-11 13:31:51 UTC) `
`loading tasks  616ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100% `
`Total 617ms `

**Comment by dgerhardt** [comment]
My mistake. Parameters of Grunt tasks have to be separated by colons instead of spaces. I've updated my previous post.
