### ISSUE TITLE
How can I disable auto generation of CSS ?

### ISSUE THREAD

**Issue by khalilmebarkia** [thm-projects/arsnova-mobile#61]
Hello ARSnova team,

I tried to make some modification on CSS file but after restarting Grunt the old CSS file will be generated.
Thank you

**Comment by Rillke** [comment]
Maybe change the less sources directly and rebase your changes in order to update.

On the other I'd be really cool, if there would be a `custom-css` option in `arsnova.properties`.

**Comment by dgerhardt** [comment]
CSS generation is done by Sencha Cmd. There is probably an option for `src/main/webapp/.sencha/app/build.properties` but you would have to look in Sencha's documentation for details. Besides that I strongly advise against modifying the generated CSS. Custom CSS is likely to break with new releases of ARSnova Mobile.

We provide a lot of theming parameters in `src/main/webapp/resources/sass/_theme.scss` for customization.
