### ISSUE TITLE
ARSnova is not defined at splashscreen.js on first page load

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-mobile#63]
ARSnova appears to maintain a cache of its own program code in the browser. However, when visiting an ARSnova instance the first time or in anonymous browsing mode, it may* happen that `splashscreen.js` attempts to start ARSnova while app.js is still loading, resulting in a JS error in the console and the application never removing the splash screen (indefinite loading throbber).

\* Requires load times > spash fadeout timeout, e.g. when compression is not turned on on server

**Comment by dgerhardt** [comment]
Thank you for the report. This is fixed for future releases.
