### ISSUE TITLE
Bad request error when attempting to establish WebSocket connection

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-mobile#64]
No impact on features. Just reporting because it isn't nice to have console errors.

How to reproduce:
- Go to https://arsnova.eu/mobile/
- Click "Dozent/in"
- Click "Gast"
- Wait a few seconds.
- In the error console you'll get

Network error:

```
"NetworkError: 400 Bad Request - https://arsnova.eu:10443/socket.io/1/"
```

JavaScript error:

```
Firefox kann keine Verbindung zu dem Server unter wss://arsnova.eu:10443/socket.io/1/ aufbauen.
https://arsnova.eu/mobile/ line 34 > eval
Line 1
```

After the error, the connection to https://arsnova.eu:10443/socket.io/?EIO=3&transport=websocket is successfully established.

**Comment by Rillke** [comment]
There is also a JS error occasionally, but I can't reproduce it right now:

```
TypeError: c.blur is not a function
https://arsnova.eu/mobile/ line 34 > eval
Line 1
```

Happens sometimes immediately after clicking a button.

**Comment by deada92** [comment]
could you fix that? Same issue here..

**Comment by knoxdj** [comment]
Sorry I have the same problem right now I'd use Apache2 is necessarily installed?
