### ISSUE TITLE
What is the purpose of the splash screen?

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-mobile#65]
The splash screen adds an artificial, fixed delay to loading the mobile application. [I and many users](http://ux.stackexchange.com/q/41682) don't like it and the brand is already prominent on the start screen, therefore I do not see the purpose in it.

**Comment by kqc-real** [comment]
With more and more ARSnova instances we had to focus the user's attention to which site he/she actually is (a Google search could be misleading):

* [ARSnova for anybody](https://arsnova.eu/mobile/#)
* [ARSnova for Hessia](https://arsnova.thm.de/mobile/)
* [ARSnova for Saxony-Anhalt](http://arsnova.uni-halle.de/mobile/)
* [ARSnova at University of Wuppertal](https://ars.zim.uni-wuppertal.de/mobile/)
* [ARSnova at University of Innsbruck](https://arsnova.uibk.ac.at/mobile/)
* [ARSnova Staging Server](https://arsnova-staging.mni.thm.de/mobile/#)

Thus the reason for the splashscreen.

**Comment by Rillke** [comment]
Thanks for the collection.

Maybe customize `ui.slogan` and add an option for a logo on the start page?
