### ISSUE TITLE
[Backend] User participation statistics?

### ISSUE THREAD

**Issue by dmoses** [thm-projects/arsnova-mobile#82]
Hello:
Is there a way for an instructor to review user responses after the activity? Are statistics - correct/incorrect responses/associated user - available for export?
Thanks,
Donald

**Comment by dmoses** [comment]
I don't see the Statistics panel ... wondering if I'm missing something in the config or install?

**Comment by dmoses** [comment]
Just bumping this ... I see the statistics panel but it is summary data and I can't seem to figure out how to get data at the activity level. Any thoughts?
Thanks.

**Comment by dgerhardt** [comment]
ARSnova only exposes aggregated answer statistics via web client/backend API and we haven't any plans to change this behavior. But user associations are available on the database level so it would be possible to modify ARSnova to get access to this data.

**Comment by dmoses** [comment]
If the moodle connector was enabled would this help facilitate that?

**Comment by dgerhardt** [comment]
No, the connector allows you to limit access to sessions based on course memberships but does not expose any additional data.

**Comment by dmoses** [comment]
Can you suggest what tables I may need to query to generate course level reports for user participation?
Thank you.
Donald

**Comment by dgerhardt** [comment]
You could use the following URL to query the CouchDB REST API:
http://localhost:5984/arsnova/_design/Answer/_view/by_user_sessionid?key=[%22<username>%22,%22<session-db-id>%22]
The response would allow you to count the number of answers per user and session.

Please note that as part of the development of ARSnova 3.0 there are changes to the database structures and query URLs will change.
