### ISSUE TITLE
Registration failed

### ISSUE THREAD

**Issue by HuntStarJonny** [thm-projects/arsnova-mobile#87]
Sorry didn't found any documentation about this.

How to configure arsnova on a self-hosted Server and create users.

Arsnova works fine on my server, but when i want to register as lecturer, i get registration failed.

**Comment by tekay** [comment]
Hi,
a few more information about your setup would be nice: did you setup backend, frontend and couchdb? Do you run the software with tomcat8 or do you use the "developer way" of running it? What is the error message you are getting?

Documentation for setting up arsnova is found here:
- https://github.com/thm-projects/arsnova-mobile/blob/master/src/site/markdown/installation.md
- https://github.com/thm-projects/arsnova-backend/blob/master/src/site/markdown/installation.md

**Comment by HuntStarJonny** [comment]
Thanks for your fast reply.

I just build the docker compose-yaml(with some changes).

Seems like the path of the config file, is the thing i searched for.
Ok lets see, if i can successfully configure, internal registration, that's what i want.

**Comment by tekay** [comment]
If you want to setup the arsnova registration (login via db account), you need to add the static files for registration and login (we have a repo for this: https://github.com/thm-projects/arsnova-customization ).
They aren't included in the docker version.
