### ISSUE TITLE
Code rendering with <hlcode> broken

### ISSUE THREAD

**Issue by Rillke** [thm-projects/arsnova-mobile#89]
![Screenshot from 2019-04-15 01-05-12](https://user-images.githubusercontent.com/2311611/56100580-d216aa80-5f1a-11e9-848b-988da3ef9276.png)

We noticed on our mobile 2.7.0 instance and on ARSnova.eu (mobile 2.7.0) that rendering of `<hlcode>` is broken. In particular, the closing  `</hlcode>`  tag appears to be replaced with a closing markdown code symbol <code>```</code> but never closed, and therefore the text following is rendered as code. See screenshot for an example.

Reproducing:
1. Go to ARSnova.eu
2. Select Student -> Demo Session -> Presentation -> Question 4

If you visit the page the first time, you may have to log in as guest and if you get the Preparation Tasks shown, you may have to navigate back and then to "presentation", then Q4.

**Comment by dgerhardt** [comment]
Thank you for reporting this issue. This is a known regression introduced by upgrading the highlight.js library in ARSnova 2.7. As a workaround the Markdown syntax (```) can be used instead of the ARSnova-specific `<hlcode>` tag.

We will change the button in a future version to insert Markdown syntax but we still want to fix this issue for existing content using `<hlcode>`.

**Comment by pawohl** [comment]
> but we still want to fix this issue for existing content using `<hlcode>`.

@dgerhardt That's awesome :)

**Comment by dgerhardt** [comment]
Fixed in 2.7.1.
