### ISSUE TITLE
Timer does not show when presenting question

### ISSUE THREAD

**Issue by sboeser** [thm-projects/arsnova-mobile#91]
When presenting a question using the question timer, the timer does not show on the question page after being activated. Only when going back to the session menu and from there back to present question the timer is displayed.

At the same time when the time is activated, in the file `/var/log/tomcat9/catalina.out` this error message occurs

```[2019-10-15 10:00:15] [info] 10:00:15,809  INFO http-nio-8080-exec-3
annotation.AnnotationAsyncExecutionInterceptor:249 - No task executor bean
found for async processing: no bean of type TaskExecutor and no bean
named 'taskExecutor' either
```

Versions:
- arsnova-mobile: 2.7.1
- arsnova-backend: 2.7.3
- tomcat 9
- Debian 10

**Comment by dgerhardt** [comment]
This has been reported to us before but we weren't able to reproduce it on our end. Could you please test the following:
* When you switch between feedback options (student role), do the feedback bars update?
* Are you able to reproduce the issue on https://arsnova.eu?

**Comment by sboeser** [comment]
* I am not quite sure what you mean by "_feedback bars_"? If I change to students role and given _instant feedback_ to the lecture, I'm directed to an empty histogram after submitting my feedback. Is this what you meant? 

* I am unable to reproduce the timer issue on  https://arsnova.eu?

If you want to test the behaviour of our system yourself, you can go to http://arsnova.physik.uni-mainz.de/. I just checked and found that the timer issue is also present when logging in as guest.

Thanks.

**Comment by dgerhardt** [comment]
> If I change to students role and given instant feedback to the lecture, I'm directed to an empty histogram after submitting my feedback. Is this what you meant?

Yes. Once you give feedback by clicking one of the three buttons on top you should instantly see a change in the chart below. If this isn't the case then there probably is an issue with the config for WebSockets which would also effect the timer.

In this case have a look at the WebSockets in `arsnova.properties`. Probably the `socketio.proxy-path=/socket.io` is commented out.

**Comment by sboeser** [comment]
Indeed, uncommenting this line fixes the issues - thank you!
